stages:
  - build
  - test
  - release

build:
  image: golang:latest
  stage: build
  script: echo 'build stage!'

test:
  image: golang:latest
  stage: test
  script: echo 'test stage!'

release:
  image: node:latest
  stage: release
  dependencies:
    - build
  before_script:
    - npm install @semantic-release/git @semantic-release/changelog -D
    - npm install -g semantic-release @semantic-release/gitlab
  script:
    - semantic-release
  only:
    - main
